[package]
name = "hello-bonsai-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
ethers = { version = "1.0", features = ["ws", "rustls"] }
hello-bonsai-contracts = { workspace = true }
hello-bonsai-methods = { workspace = true }
hex = "0.4"
reqwest = "0.11"
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true }
tokio = "1.24"
